package pl.pej.malpompaaligxilo

import pl.pej.malpompaaligxilo.form.{FieldName, Field}
import pl.pej.malpompaaligxilo.form.field.{EnumOption, SelectField}
import pl.pej.malpompaaligxilo.util._


package object jes2015 {
  implicit def tuple22enumOption(tuple2: (String, I18nable[String])): EnumOption =
    EnumOption(tuple2._1, tuple2._2)

  def countryField(implicit poCfg: PoCfg) = Field[EnumOption](
    name = "lando",
    caption = I18n.po("Lando"),
    required = true,
    `type` = SelectField(
      options = List[EnumOption](
        EnumOption("ad", I18nString("eo" -> "Andoro", "hu" -> "Andorra", "pl" -> "Andora", "fr" -> "Andorre")),
        EnumOption("ae", I18nString("eo" -> "Unuiĝintaj Arabaj Emirlandos", "hu" -> "Egyesült Arab Emirátus", "pl" -> "Zjednoczone Emiraty Arabskie", "fr" -> "Émirats arabes unis")),
        EnumOption("af", I18nString("eo" -> "Afganujo", "hu" -> "Afganisztán", "pl" -> "Afganistan", "fr" -> "Afghanistan")),
        EnumOption("ag", I18nString("eo" -> "Antigvo-Barbudo", "hu" -> "Antigua és Barbuda", "pl" -> "Antigua i Barbuda", "fr" -> "Antigua-et-Barbuda")),
        EnumOption("al", I18nString("eo" -> "Albanujo", "hu" -> "Albánia", "pl" -> "Albania", "fr" -> "Albanie")),
        EnumOption("am", I18nString("eo" -> "Armenujo", "hu" -> "Örményország", "pl" -> "Armenia", "fr" -> "Arménie")),
        EnumOption("ao", I18nString("eo" -> "Angolo", "hu" -> "Angola", "pl" -> "Angola", "fr" -> "Angola")),
        EnumOption("ar", I18nString("eo" -> "Argentino", "hu" -> "Argentína", "pl" -> "Argentyna", "fr" -> "Argentine")),
        EnumOption("at", I18nString("eo" -> "Aŭstrujo", "hu" -> "Ausztria", "pl" -> "Austria", "fr" -> "Autriche")),
        EnumOption("au", I18nString("eo" -> "Aŭstralio", "hu" -> "Ausztrália", "pl" -> "Australia", "fr" -> "Australie")),
        EnumOption("az", I18nString("eo" -> "Azerbajĝano", "hu" -> "Azerbajdzsán", "pl" -> "Azerbejdżan", "fr" -> "Azerbaïdjan")),
        EnumOption("ba", I18nString("eo" -> "Bosnio-Hercegovino", "hu" -> "Bosznia-Hercegovina", "pl" -> "Bośnia i Hercegowina", "fr" -> "Bosnie-Herzégovine")),
        EnumOption("bb", I18nString("eo" -> "Barbado", "hu" -> "Barbados", "pl" -> "Barbados", "fr" -> "Barbade")),
        EnumOption("bd", I18nString("eo" -> "Bangladeŝo", "hu" -> "Banglades", "pl" -> "Bangladesz", "fr" -> "Bangladesh")),
        EnumOption("be", I18nString("eo" -> "Belgujo", "hu" -> "Belgium", "pl" -> "Belgia", "fr" -> "Belgique")),
        EnumOption("bf", I18nString("eo" -> "Burkino", "hu" -> "Burkina Faso", "pl" -> "Burkina Faso", "fr" -> "Burkina Faso")),
        EnumOption("bg", I18nString("eo" -> "Bulgarujo", "hu" -> "Bulgária", "pl" -> "Bułgaria", "fr" -> "Bulgarie")),
        EnumOption("bh", I18nString("eo" -> "Barejno", "hu" -> "Bahrein", "pl" -> "Bahrajn", "fr" -> "Bahreïn")),
        EnumOption("bi", I18nString("eo" -> "Burundo", "hu" -> "Burundi", "pl" -> "Burundi", "fr" -> "Burundi")),
        EnumOption("bj", I18nString("eo" -> "Benino", "hu" -> "Benin", "pl" -> "Benin", "fr" -> "Bénin")),
        EnumOption("bn", I18nString("eo" -> "Brunejo", "hu" -> "Brunei", "pl" -> "Brunei Darussalam", "fr" -> "Brunéi Darussalam")),
        EnumOption("bo", I18nString("eo" -> "Bolivio", "hu" -> "Bolívia", "pl" -> "Boliwia", "fr" -> "Bolivie")),
        EnumOption("br", I18nString("eo" -> "Brazilo", "hu" -> "Brazília", "pl" -> "Brazylia", "fr" -> "Brésil")),
        EnumOption("bs", I18nString("eo" -> "Bahamoj", "hu" -> "Bahamák", "pl" -> "Bahamy", "fr" -> "Bahamas")),
        EnumOption("bt", I18nString("eo" -> "Butano", "hu" -> "Bhután", "pl" -> "Bhutan", "fr" -> "Bhoutan")),
        EnumOption("bw", I18nString("eo" -> "Bocvano", "hu" -> "Botswana", "pl" -> "Botswana", "fr" -> "Botswana")),
        EnumOption("by", I18nString("eo" -> "Belorusujo", "hu" -> "Fehéroroszország", "pl" -> "Białoruś", "fr" -> "Bélarus")),
        EnumOption("bz", I18nString("eo" -> "Belizo", "hu" -> "Belize", "pl" -> "Belize", "fr" -> "Belize")),
        EnumOption("ca", I18nString("eo" -> "Kanado", "hu" -> "Kanada", "pl" -> "Kanada", "fr" -> "Canada")),
        EnumOption("cd", I18nString("eo" -> "Demokratia Respubliko Kongo", "hu" -> "Kongó - Kinshasa", "pl" -> "Demokratyczna Republika Konga", "fr" -> "République démocratique du Congo")),
        EnumOption("cf", I18nString("eo" -> "Centr-Afrika Respubliko", "hu" -> "Közép-afrikai Köztársaság", "pl" -> "Republika Środkowoafrykańska", "fr" -> "République centrafricaine")),
        EnumOption("cg", I18nString("eo" -> "Kongolo", "hu" -> "Kongó", "pl" -> "Kongo", "fr" -> "Congo")),
        EnumOption("ch", I18nString("eo" -> "Svisujo", "hu" -> "Svájc", "pl" -> "Szwajcaria", "fr" -> "Suisse")),
        EnumOption("ci", I18nString("eo" -> "Ebur-Bordo", "hu" -> "Elefántcsontpart", "pl" -> "Wybrzeże Kości Słoniowej", "fr" -> "Côte d’Ivoire")),
        EnumOption("cl", I18nString("eo" -> "Ĉilio", "hu" -> "Chile", "pl" -> "Chile", "fr" -> "Chili")),
        EnumOption("cm", I18nString("eo" -> "Kameruno", "hu" -> "Kamerun", "pl" -> "Kamerun", "fr" -> "Cameroun")),
        EnumOption("cn", I18nString("eo" -> "Ĉinujo", "hu" -> "Kína", "pl" -> "Chiny", "fr" -> "Chine")),
        EnumOption("co", I18nString("eo" -> "Kolombio", "hu" -> "Kolumbia", "pl" -> "Kolumbia", "fr" -> "Colombie")),
        EnumOption("cr", I18nString("eo" -> "Kostariko", "hu" -> "Costa Rica", "pl" -> "Kostaryka", "fr" -> "Costa Rica")),
        EnumOption("cu", I18nString("eo" -> "Kubo", "hu" -> "Kuba", "pl" -> "Kuba", "fr" -> "Cuba")),
        EnumOption("cv", I18nString("eo" -> "Kabo-Verdo", "hu" -> "Zöld-foki Köztársaság", "pl" -> "Republika Zielonego Przylądka", "fr" -> "Cap-Vert")),
        EnumOption("cy", I18nString("eo" -> "Kipro", "hu" -> "Ciprus", "pl" -> "Cypr", "fr" -> "Chypre")),
        EnumOption("cz", I18nString("eo" -> "Ĉeĥujo", "hu" -> "Csehország", "pl" -> "Czechy", "fr" -> "République tchèque")),
        EnumOption("de", I18nString("eo" -> "Germanujo", "hu" -> "Németország", "pl" -> "Niemcy", "fr" -> "Allemagne")),
        EnumOption("dj", I18nString("eo" -> "Ĝibutio", "hu" -> "Dzsibuti", "pl" -> "Dżibuti", "fr" -> "Djibouti")),
        EnumOption("dk", I18nString("eo" -> "Danujo", "hu" -> "Dánia", "pl" -> "Dania", "fr" -> "Danemark")),
        EnumOption("dm", I18nString("eo" -> "Dominiko", "hu" -> "Dominika", "pl" -> "Dominika", "fr" -> "Dominique")),
        EnumOption("do", I18nString("eo" -> "Domingo", "hu" -> "Dominikai Köztársaság", "pl" -> "Republika Dominikańska", "fr" -> "République dominicaine")),
        EnumOption("dz", I18nString("eo" -> "Alĝerio", "hu" -> "Algéria", "pl" -> "Algieria", "fr" -> "Algérie")),
        EnumOption("ec", I18nString("eo" -> "Ekvadoro", "hu" -> "Ecuador", "pl" -> "Ekwador", "fr" -> "Équateur")),
        EnumOption("ee", I18nString("eo" -> "Estonujo", "hu" -> "Észtország", "pl" -> "Estonia", "fr" -> "Estonie")),
        EnumOption("eg", I18nString("eo" -> "Egipto", "hu" -> "Egyiptom", "pl" -> "Egipt", "fr" -> "Égypte")),
        EnumOption("er", I18nString("eo" -> "Eritreo", "hu" -> "Eritrea", "pl" -> "Erytrea", "fr" -> "Érythrée")),
        EnumOption("es", I18nString("eo" -> "Hispanujo", "hu" -> "Spanyolország", "pl" -> "Hiszpania", "fr" -> "Espagne")),
        EnumOption("et", I18nString("eo" -> "Etiopujo", "hu" -> "Etiópia", "pl" -> "Etiopia", "fr" -> "Éthiopie")),
        EnumOption("fi", I18nString("eo" -> "Finnlando", "hu" -> "Finnország", "pl" -> "Finlandia", "fr" -> "Finlande")),
        EnumOption("fj", I18nString("eo" -> "Fiĝoj", "hu" -> "Fidzsi", "pl" -> "Fidżi", "fr" -> "Fidji")),
        EnumOption("fm", I18nString("eo" -> "Mikronezio", "hu" -> "Mikronézia", "pl" -> "Federalne Stany Mikronezji", "fr" -> "États fédérés de Micronésie")),
        EnumOption("fr", I18nString("eo" -> "Francujo", "hu" -> "Franciaország", "pl" -> "Francja", "fr" -> "France")),
        EnumOption("ga", I18nString("eo" -> "Gabono", "hu" -> "Gabon", "pl" -> "Gabon", "fr" -> "Gabon")),
        EnumOption("gb", I18nString("eo" -> "Unuiĝinta Reĝlando", "hu" -> "Egyesült Királyság", "pl" -> "Wielka Brytania", "fr" -> "Royaume-Uni")),
        EnumOption("gd", I18nString("eo" -> "Grenado", "hu" -> "Grenada", "pl" -> "Grenada", "fr" -> "Grenade")),
        EnumOption("ge", I18nString("eo" -> "Kartvelujo", "hu" -> "Grúzia", "pl" -> "Gruzja", "fr" -> "Géorgie")),
        EnumOption("gh", I18nString("eo" -> "Ganao", "hu" -> "Ghána", "pl" -> "Ghana", "fr" -> "Ghana")),
        EnumOption("gm", I18nString("eo" -> "Gambio", "hu" -> "Gambia", "pl" -> "Gambia", "fr" -> "Gambie")),
        EnumOption("gn", I18nString("eo" -> "Gvineo", "hu" -> "Guinea", "pl" -> "Gwinea", "fr" -> "Guinée")),
        EnumOption("gq", I18nString("eo" -> "Ekvatora Gvineo", "hu" -> "Egyenlítői-Guinea", "pl" -> "Gwinea Równikowa", "fr" -> "Guinée équatoriale")),
        EnumOption("gr", I18nString("eo" -> "Grekujo", "hu" -> "Görögország", "pl" -> "Grecja", "fr" -> "Grèce")),
        EnumOption("gt", I18nString("eo" -> "Gvatemalo", "hu" -> "Guatemala", "pl" -> "Gwatemala", "fr" -> "Guatemala")),
        EnumOption("gw", I18nString("eo" -> "Gvineo-Bisaŭo", "hu" -> "Guinea-Bissau", "pl" -> "Gwinea Bissau", "fr" -> "Guinée-Bissau")),
        EnumOption("gy", I18nString("eo" -> "Gujano", "hu" -> "Guyana", "pl" -> "Gujana", "fr" -> "Guyana")),
        EnumOption("hn", I18nString("eo" -> "Honduro", "hu" -> "Honduras", "pl" -> "Honduras", "fr" -> "Honduras")),
        EnumOption("hr", I18nString("eo" -> "Kroatujo", "hu" -> "Horvátország", "pl" -> "Chorwacja", "fr" -> "Croatie")),
        EnumOption("ht", I18nString("eo" -> "Haitio", "hu" -> "Haiti", "pl" -> "Haiti", "fr" -> "Haïti")),
        EnumOption("hu", I18nString("eo" -> "Hungarujo", "hu" -> "Magyarország", "pl" -> "Węgry", "fr" -> "Hongrie")),
        EnumOption("id", I18nString("eo" -> "Indonezio", "hu" -> "Indonézia", "pl" -> "Indonezja", "fr" -> "Indonésie")),
        EnumOption("ie", I18nString("eo" -> "Irlando", "hu" -> "Írország", "pl" -> "Irlandia", "fr" -> "Irlande")),
        EnumOption("il", I18nString("eo" -> "Israelo", "hu" -> "Izrael", "pl" -> "Izrael", "fr" -> "Israël")),
        EnumOption("in", I18nString("eo" -> "Hindujo", "hu" -> "India", "pl" -> "Indie", "fr" -> "Inde")),
        EnumOption("iq", I18nString("eo" -> "Irako", "hu" -> "Irak", "pl" -> "Irak", "fr" -> "Irak")),
        EnumOption("ir", I18nString("eo" -> "Irano", "hu" -> "Irán", "pl" -> "Iran", "fr" -> "Iran")),
        EnumOption("is", I18nString("eo" -> "Islando", "hu" -> "Izland", "pl" -> "Islandia", "fr" -> "Islande")),
        EnumOption("it", I18nString("eo" -> "Italujo", "hu" -> "Olaszország", "pl" -> "Włochy", "fr" -> "Italie")),
        EnumOption("jm", I18nString("eo" -> "Jamajko", "hu" -> "Jamaica", "pl" -> "Jamajka", "fr" -> "Jamaïque")),
        EnumOption("jo", I18nString("eo" -> "Jordanio", "hu" -> "Jordánia", "pl" -> "Jordania", "fr" -> "Jordanie")),
        EnumOption("jp", I18nString("eo" -> "Japanujo", "hu" -> "Japán", "pl" -> "Japonia", "fr" -> "Japon")),
        EnumOption("ke", I18nString("eo" -> "Kenjo", "hu" -> "Kenya", "pl" -> "Kenia", "fr" -> "Kenya")),
        EnumOption("kg", I18nString("eo" -> "Kirgizistano", "hu" -> "Kirgizisztán", "pl" -> "Kirgistan", "fr" -> "Kirghizistan")),
        EnumOption("kh", I18nString("eo" -> "Kamboĝo", "hu" -> "Kambodzsa", "pl" -> "Kambodża", "fr" -> "Cambodge")),
        EnumOption("ki", I18nString("eo" -> "Kiribato", "hu" -> "Kiribati", "pl" -> "Kiribati", "fr" -> "Kiribati")),
        EnumOption("km", I18nString("eo" -> "Komoroj", "hu" -> "Comore-szigetek", "pl" -> "Komory", "fr" -> "Comores")),
        EnumOption("kn", I18nString("eo" -> "Sent-Kristofo kaj Neviso", "hu" -> "Saint Kitts és Nevis", "pl" -> "Saint Kitts i Nevis", "fr" -> "Saint-Kitts-et-Nevis")),
        EnumOption("kp", I18nString("eo" -> "Nord-Koreo", "hu" -> "Észak-Korea", "pl" -> "Korea Północna", "fr" -> "Corée du Nord")),
        EnumOption("kr", I18nString("eo" -> "Sud-Koreo", "hu" -> "Dél-Korea", "pl" -> "Korea Południowa", "fr" -> "Corée du Sud")),
        EnumOption("kw", I18nString("eo" -> "Kuvajto", "hu" -> "Kuvait", "pl" -> "Kuwejt", "fr" -> "Koweït")),
        EnumOption("kz", I18nString("eo" -> "Kazaĥstano", "hu" -> "Kazahsztán", "pl" -> "Kazachstan", "fr" -> "Kazakhstan")),
        EnumOption("la", I18nString("eo" -> "Laoso", "hu" -> "Laosz", "pl" -> "Laos", "fr" -> "Laos")),
        EnumOption("lb", I18nString("eo" -> "Libano", "hu" -> "Libanon", "pl" -> "Liban", "fr" -> "Liban")),
        EnumOption("lc", I18nString("eo" -> "Sent-Lucio", "hu" -> "Santa Lucia", "pl" -> "Saint Lucia", "fr" -> "Sainte-Lucie")),
        EnumOption("li", I18nString("eo" -> "Liĥtenŝtejno", "hu" -> "Liechtenstein", "pl" -> "Liechtenstein", "fr" -> "Liechtenstein")),
        EnumOption("lk", I18nString("eo" -> "Sri-Lanko", "hu" -> "Srí Lanka", "pl" -> "Sri Lanka", "fr" -> "Sri Lanka")),
        EnumOption("lr", I18nString("eo" -> "Liberio", "hu" -> "Libéria", "pl" -> "Liberia", "fr" -> "Libéria")),
        EnumOption("ls", I18nString("eo" -> "Lesoto", "hu" -> "Lesotho", "pl" -> "Lesotho", "fr" -> "Lesotho")),
        EnumOption("lt", I18nString("eo" -> "Litovujo", "hu" -> "Litvánia", "pl" -> "Litwa", "fr" -> "Lituanie")),
        EnumOption("lu", I18nString("eo" -> "Luksemburgo", "hu" -> "Luxemburg", "pl" -> "Luksemburg", "fr" -> "Luxembourg")),
        EnumOption("lv", I18nString("eo" -> "Latvujo", "hu" -> "Lettország", "pl" -> "Łotwa", "fr" -> "Lettonie")),
        EnumOption("ly", I18nString("eo" -> "Libio", "hu" -> "Líbia", "pl" -> "Libia", "fr" -> "Libye")),
        EnumOption("ma", I18nString("eo" -> "Maroko", "hu" -> "Marokkó", "pl" -> "Maroko", "fr" -> "Maroc")),
        EnumOption("mc", I18nString("eo" -> "Monako", "hu" -> "Monaco", "pl" -> "Monako", "fr" -> "Monaco")),
        EnumOption("md", I18nString("eo" -> "Moldavujo", "hu" -> "Moldova", "pl" -> "Mołdawia", "fr" -> "Moldavie")),
        EnumOption("me", I18nString("eo" -> "ME", "hu" -> "Montenegró", "pl" -> "Czarnogóra", "fr" -> "Monténégro")),
        EnumOption("mg", I18nString("eo" -> "Madagaskaro", "hu" -> "Madagaszkár", "pl" -> "Madagaskar", "fr" -> "Madagascar")),
        EnumOption("mh", I18nString("eo" -> "Marŝaloj", "hu" -> "Marshall-szigetek", "pl" -> "Wyspy Marshalla", "fr" -> "Îles Marshall")),
        EnumOption("mk", I18nString("eo" -> "Makedonujo", "hu" -> "Macedónia", "pl" -> "Macedonia", "fr" -> "Macédoine")),
        EnumOption("ml", I18nString("eo" -> "Malio", "hu" -> "Mali", "pl" -> "Mali", "fr" -> "Mali")),
        EnumOption("mm", I18nString("eo" -> "Mjanmao", "hu" -> "Mianmar", "pl" -> "Birma", "fr" -> "Myanmar")),
        EnumOption("mn", I18nString("eo" -> "Mongolujo", "hu" -> "Mongólia", "pl" -> "Mongolia", "fr" -> "Mongolie")),
        EnumOption("mr", I18nString("eo" -> "Maŭritanujo", "hu" -> "Mauritánia", "pl" -> "Mauretania", "fr" -> "Mauritanie")),
        EnumOption("mt", I18nString("eo" -> "Malto", "hu" -> "Málta", "pl" -> "Malta", "fr" -> "Malte")),
        EnumOption("mu", I18nString("eo" -> "Maŭricio", "hu" -> "Mauritius", "pl" -> "Mauritius", "fr" -> "Maurice")),
        EnumOption("mv", I18nString("eo" -> "Maldivoj", "hu" -> "Maldív-szigetek", "pl" -> "Malediwy", "fr" -> "Maldives")),
        EnumOption("mw", I18nString("eo" -> "Malavio", "hu" -> "Malawi", "pl" -> "Malawi", "fr" -> "Malawi")),
        EnumOption("mx", I18nString("eo" -> "Meksiko", "hu" -> "Mexikó", "pl" -> "Meksyk", "fr" -> "Mexique")),
        EnumOption("my", I18nString("eo" -> "Malajzio", "hu" -> "Malajzia", "pl" -> "Malezja", "fr" -> "Malaisie")),
        EnumOption("mz", I18nString("eo" -> "Mozambiko", "hu" -> "Mozambik", "pl" -> "Mozambik", "fr" -> "Mozambique")),
        EnumOption("na", I18nString("eo" -> "Namibio", "hu" -> "Namíbia", "pl" -> "Namibia", "fr" -> "Namibie")),
        EnumOption("ne", I18nString("eo" -> "Niĝero", "hu" -> "Niger", "pl" -> "Niger", "fr" -> "Niger")),
        EnumOption("ng", I18nString("eo" -> "Niĝerio", "hu" -> "Nigéria", "pl" -> "Nigeria", "fr" -> "Nigéria")),
        EnumOption("ni", I18nString("eo" -> "Nikaragvo", "hu" -> "Nicaragua", "pl" -> "Nikaragua", "fr" -> "Nicaragua")),
        EnumOption("nl", I18nString("eo" -> "Nederlando", "hu" -> "Hollandia", "pl" -> "Holandia", "fr" -> "Pays-Bas")),
        EnumOption("no", I18nString("eo" -> "Norvegujo", "hu" -> "Norvégia", "pl" -> "Norwegia", "fr" -> "Norvège")),
        EnumOption("np", I18nString("eo" -> "Nepalo", "hu" -> "Nepál", "pl" -> "Nepal", "fr" -> "Népal")),
        EnumOption("nr", I18nString("eo" -> "Nauro", "hu" -> "Nauru", "pl" -> "Nauru", "fr" -> "Nauru")),
        EnumOption("nz", I18nString("eo" -> "Nov-Zelando", "hu" -> "Új-Zéland", "pl" -> "Nowa Zelandia", "fr" -> "Nouvelle-Zélande")),
        EnumOption("om", I18nString("eo" -> "Omano", "hu" -> "Omán", "pl" -> "Oman", "fr" -> "Oman")),
        EnumOption("pa", I18nString("eo" -> "Panamo", "hu" -> "Panama", "pl" -> "Panama", "fr" -> "Panama")),
        EnumOption("pe", I18nString("eo" -> "Peruo", "hu" -> "Peru", "pl" -> "Peru", "fr" -> "Pérou")),
        EnumOption("pg", I18nString("eo" -> "Papuo-Nov-Gvineo", "hu" -> "Pápua Új-Guinea", "pl" -> "Papua Nowa Gwinea", "fr" -> "Papouasie-Nouvelle-Guinée")),
        EnumOption("ph", I18nString("eo" -> "Filipinoj", "hu" -> "Fülöp-szigetek", "pl" -> "Filipiny", "fr" -> "Philippines")),
        EnumOption("pk", I18nString("eo" -> "Pakistano", "hu" -> "Pakisztán", "pl" -> "Pakistan", "fr" -> "Pakistan")),
        EnumOption("pl", I18nString("eo" -> "Pollando", "hu" -> "Lengyelország", "pl" -> "Polska", "fr" -> "Pologne")),
        EnumOption("pt", I18nString("eo" -> "Portugalujo", "hu" -> "Portugália", "pl" -> "Portugalia", "fr" -> "Portugal")),
        EnumOption("pw", I18nString("eo" -> "Belaŭo", "hu" -> "Palau", "pl" -> "Palau", "fr" -> "Palaos")),
        EnumOption("py", I18nString("eo" -> "Paragvajo", "hu" -> "Paraguay", "pl" -> "Paragwaj", "fr" -> "Paraguay")),
        EnumOption("qa", I18nString("eo" -> "Kataro", "hu" -> "Katar", "pl" -> "Katar", "fr" -> "Qatar")),
        EnumOption("ro", I18nString("eo" -> "Rumanujo", "hu" -> "Románia", "pl" -> "Rumunia", "fr" -> "Roumanie")),
        EnumOption("rs", I18nString("eo" -> "RS", "hu" -> "Szerbia", "pl" -> "Serbia", "fr" -> "Serbie")),
        EnumOption("ru", I18nString("eo" -> "Rusujo", "hu" -> "Oroszország", "pl" -> "Rosja", "fr" -> "Russie")),
        EnumOption("rw", I18nString("eo" -> "Ruando", "hu" -> "Ruanda", "pl" -> "Rwanda", "fr" -> "Rwanda")),
        EnumOption("sa", I18nString("eo" -> "Saŭda Arabujo", "hu" -> "Szaúd-Arábia", "pl" -> "Arabia Saudyjska", "fr" -> "Arabie saoudite")),
        EnumOption("sb", I18nString("eo" -> "Salomonoj", "hu" -> "Salamon-szigetek", "pl" -> "Wyspy Salomona", "fr" -> "Îles Salomon")),
        EnumOption("sc", I18nString("eo" -> "Sejŝeloj", "hu" -> "Seychelle-szigetek", "pl" -> "Seszele", "fr" -> "Seychelles")),
        EnumOption("sd", I18nString("eo" -> "Sudano", "hu" -> "Szudán", "pl" -> "Sudan", "fr" -> "Soudan")),
        EnumOption("se", I18nString("eo" -> "Svedujo", "hu" -> "Svédország", "pl" -> "Szwecja", "fr" -> "Suède")),
        EnumOption("sg", I18nString("eo" -> "Singapuro", "hu" -> "Szingapúr", "pl" -> "Singapur", "fr" -> "Singapour")),
        EnumOption("si", I18nString("eo" -> "Slovenujo", "hu" -> "Szlovénia", "pl" -> "Słowenia", "fr" -> "Slovénie")),
        EnumOption("sk", I18nString("eo" -> "Slovakujo", "hu" -> "Szlovákia", "pl" -> "Słowacja", "fr" -> "Slovaquie")),
        EnumOption("sl", I18nString("eo" -> "Siera-Leono", "hu" -> "Sierra Leone", "pl" -> "Sierra Leone", "fr" -> "Sierra Leone")),
        EnumOption("sm", I18nString("eo" -> "San-Marino", "hu" -> "San Marino", "pl" -> "San Marino", "fr" -> "Saint-Marin")),
        EnumOption("sn", I18nString("eo" -> "Senegalo", "hu" -> "Szenegál", "pl" -> "Senegal", "fr" -> "Sénégal")),
        EnumOption("so", I18nString("eo" -> "Somalujo", "hu" -> "Szomália", "pl" -> "Somalia", "fr" -> "Somalie")),
        EnumOption("sr", I18nString("eo" -> "Surinamo", "hu" -> "Suriname", "pl" -> "Surinam", "fr" -> "Suriname")),
        EnumOption("st", I18nString("eo" -> "Sao-Tomeo kaj Principeo", "hu" -> "Sao Tomé és Príncipe", "pl" -> "Wyspy Świętego Tomasza i Książęca", "fr" -> "Sao Tomé-et-Principe")),
        EnumOption("sv", I18nString("eo" -> "Salvadoro", "hu" -> "Salvador", "pl" -> "Salwador", "fr" -> "El Salvador")),
        EnumOption("sy", I18nString("eo" -> "Sirio", "hu" -> "Szíria", "pl" -> "Syria", "fr" -> "Syrie")),
        EnumOption("sz", I18nString("eo" -> "Svazilando", "hu" -> "Szváziföld", "pl" -> "Suazi", "fr" -> "Swaziland")),
        EnumOption("td", I18nString("eo" -> "Ĉado", "hu" -> "Csád", "pl" -> "Czad", "fr" -> "Tchad")),
        EnumOption("tg", I18nString("eo" -> "Togolo", "hu" -> "Togo", "pl" -> "Togo", "fr" -> "Togo")),
        EnumOption("th", I18nString("eo" -> "Tajlando", "hu" -> "Thaiföld", "pl" -> "Tajlandia", "fr" -> "Thaïlande")),
        EnumOption("tj", I18nString("eo" -> "Taĝikujo", "hu" -> "Tadzsikisztán", "pl" -> "Tadżykistan", "fr" -> "Tadjikistan")),
        EnumOption("tl", I18nString("eo" -> "TL", "hu" -> "Kelet-Timor", "pl" -> "Timor Wschodni", "fr" -> "Timor oriental")),
        EnumOption("tm", I18nString("eo" -> "Turkmenujo", "hu" -> "Türkmenisztán", "pl" -> "Turkmenistan", "fr" -> "Turkménistan")),
        EnumOption("tn", I18nString("eo" -> "Tunizio", "hu" -> "Tunézia", "pl" -> "Tunezja", "fr" -> "Tunisie")),
        EnumOption("to", I18nString("eo" -> "Tongo", "hu" -> "Tonga", "pl" -> "Tonga", "fr" -> "Tonga")),
        EnumOption("tr", I18nString("eo" -> "Turkujo", "hu" -> "Törökország", "pl" -> "Turcja", "fr" -> "Turquie")),
        EnumOption("tt", I18nString("eo" -> "Trinidado kaj Tobago", "hu" -> "Trinidad és Tobago", "pl" -> "Trynidad i Tobago", "fr" -> "Trinité-et-Tobago")),
        EnumOption("tv", I18nString("eo" -> "Tuvalo", "hu" -> "Tuvalu", "pl" -> "Tuvalu", "fr" -> "Tuvalu")),
        EnumOption("tw", I18nString("eo" -> "Tajvano", "hu" -> "Tajvan", "pl" -> "Tajwan", "fr" -> "Taïwan")),
        EnumOption("tz", I18nString("eo" -> "Tanzanio", "hu" -> "Tanzánia", "pl" -> "Tanzania", "fr" -> "Tanzanie")),
        EnumOption("ua", I18nString("eo" -> "Ukrajno", "hu" -> "Ukrajna", "pl" -> "Ukraina", "fr" -> "Ukraine")),
        EnumOption("ug", I18nString("eo" -> "Ugando", "hu" -> "Uganda", "pl" -> "Uganda", "fr" -> "Ouganda")),
        EnumOption("us", I18nString("eo" -> "Usono", "hu" -> "Egyesült Államok", "pl" -> "Stany Zjednoczone", "fr" -> "États-Unis")),
        EnumOption("uy", I18nString("eo" -> "Urugvajo", "hu" -> "Uruguay", "pl" -> "Urugwaj", "fr" -> "Uruguay")),
        EnumOption("uz", I18nString("eo" -> "Uzbekujo", "hu" -> "Üzbegisztán", "pl" -> "Uzbekistan", "fr" -> "Ouzbékistan")),
        EnumOption("va", I18nString("eo" -> "Vatikano", "hu" -> "Vatikán", "pl" -> "Watykan", "fr" -> "État de la Cité du Vatican")),
        EnumOption("vc", I18nString("eo" -> "Sent-Vincento kaj la Grenadinoj", "hu" -> "Saint Vincent és Grenadines", "pl" -> "Saint Vincent i Grenadyny", "fr" -> "Saint-Vincent-et-les Grenadines")),
        EnumOption("ve", I18nString("eo" -> "Venezuelo", "hu" -> "Venezuela", "pl" -> "Wenezuela", "fr" -> "Venezuela")),
        EnumOption("vn", I18nString("eo" -> "Vjetnamo", "hu" -> "Vietnam", "pl" -> "Wietnam", "fr" -> "Viêt Nam")),
        EnumOption("vu", I18nString("eo" -> "Vanuatuo", "hu" -> "Vanuatu", "pl" -> "Vanuatu", "fr" -> "Vanuatu")),
        EnumOption("ws", I18nString("eo" -> "Samoo", "hu" -> "Szamoa", "pl" -> "Samoa", "fr" -> "Samoa")),
        EnumOption("ye", I18nString("eo" -> "Jemeno", "hu" -> "Jemen", "pl" -> "Jemen", "fr" -> "Yémen")),
        EnumOption("za", I18nString("eo" -> "Sud-Afriko", "hu" -> "Dél-Afrika", "pl" -> "Republika Południowej Afryki", "fr" -> "Afrique du Sud")),
        EnumOption("zm", I18nString("eo" -> "Zambio", "hu" -> "Zambia", "pl" -> "Zambia", "fr" -> "Zambie")),
        EnumOption("zw", I18nString("eo" -> "Zimbabvo", "hu" -> "Zimbabwe", "pl" -> "Zimbabwe", "fr" -> "Zimbabwe"))
      ).sortBy(_.caption("eo"))(pl.pej.util.EsperantoOrdering.ordering),
      notSelected = Some(EnumOption("nenio", I18n.po("bv. elekti landon")))
    )
  )

}
