package pl.pej.malpompaaligxilo

import pl.pej.malpompaaligxilo.form.{FieldName, Field}
import pl.pej.malpompaaligxilo.form.field.{EnumOption, SelectField}
import pl.pej.malpompaaligxilo.util._


package object jes2015 {
  implicit def tuple22enumOption(tuple2: (String, I18nable[String])): EnumOption =
    EnumOption(tuple2._1, tuple2._2)

//  val landoj = List("cy", "cz", "cr", "cu", "cv", "ci", "ch", "cm", "cl", "co", "cn", "ca", "cd", "cg", "cf", "fj", "np", "fi", "sm", "so", "nz", "sc", "sb", "se", "sd", "sg", "to", "sy", "na", "ng", "ne", "fr", "ni", "no", "nl", "sv", "tg", "ve", "mz", "my", "mx", "mr", "mw", "mv", "mu", "mt", "mk", "mh", "mn", "mm", "ml", "mc", "vc", "ma", "ru", "mg", "me", "md", "sl", "az", "au", "at", "ar", "ao", "am", "al", "ag", "af", "ae", "ad", "ly", "lr", "ls", "lt", "lu", "lv", "li", "ye", "lk", "sz", "la", "lb", "lc", "zw", "ir", "nr", "us", "sn", "dz", "sk", "pw", "ro", "de", "dj", "dk", "dm", "do", "ke", "pl", "kg", "sa", "ki", "kh", "tj", "fm", "km", "tm", "tn", "kn", "kp", "tr", "kr", "tt", "kw", "tw", "tz", "kz", "vu", "ws", "sr", "jp", "jo", "jm", "qa", "bw", "bt", "zm", "br", "bs", "bz", "by", "bf", "bg", "bd", "be", "bb", "ba", "bn", "bo", "bj", "th", "bh", "bi", "ie", "id", "in", "il", "st", "rw", "it", "is", "rs", "iq", "gd", "es", "er", "et", "td", "tl", "ec", "eg", "ee", "va", "vn", "ua", "ug", "hn", "ht", "hu", "pt", "hr", "uz", "uy", "py", "tv", "za", "gm", "gn", "ph", "gh", "pk", "ge", "pe", "pg", "ga", "pa", "gb", "gy", "si", "om", "gt", "gw", "gq", "gr", "ss")

//  val landojPo = PoCfg.fromResources(getClass,
//    "eo" -> "/landoj_eo.po",
//    "pl" -> "/landoj_pl.po"
//  )

  def countryField(implicit poCfg: PoCfg) = Field[EnumOption](
    name = "lando",
    caption = I18nString(
      "eo" -> "Lando",
      "pl" -> "Kraj"
    ),
    required = true,
    `type` = SelectField(
      options = List[EnumOption](
        EnumOption("cy", I18nString("eo" -> "Kipro", "pl" -> "Cypr")),
        EnumOption("cz", I18nString("eo" -> "\u0108e\u0125ujo", "pl" -> "Czechy")),
        EnumOption("cr", I18nString("eo" -> "Kostariko", "pl" -> "Kostaryka")),
        EnumOption("cu", I18nString("eo" -> "Kubo", "pl" -> "Kuba")),
        EnumOption("cv", I18nString("eo" -> "Kabo-Verdo", "pl" -> "Republika Zielonego Przyl\u0105dka")),
        EnumOption("ci", I18nString("eo" -> "Ebur-Bordo", "pl" -> "Wybrze\u017ce Ko\u015bci S\u0142oniowej")),
        EnumOption("ch", I18nString("eo" -> "Svisujo", "pl" -> "Szwajcaria")),
        EnumOption("cm", I18nString("eo" -> "Kameruno", "pl" -> "Kamerun")),
        EnumOption("cl", I18nString("eo" -> "\u0108ilio", "pl" -> "Chile")),
        EnumOption("co", I18nString("eo" -> "Kolombio", "pl" -> "Kolumbia")),
        EnumOption("cn", I18nString("eo" -> "\u0108inujo", "pl" -> "Chiny")),
        EnumOption("ca", I18nString("eo" -> "Kanado", "pl" -> "Kanada")),
        EnumOption("cd", I18nString("eo" -> "CD", "pl" -> "Demokratyczna Republika Konga")),
        EnumOption("cg", I18nString("eo" -> "Kongolo", "pl" -> "Kongo")),
        EnumOption("cf", I18nString("eo" -> "Centr-Afrika Respubliko", "pl" -> "Republika \u015arodkowoafryka\u0144ska")),
        EnumOption("fj", I18nString("eo" -> "Fi\u011doj", "pl" -> "Fid\u017ci")),
        EnumOption("np", I18nString("eo" -> "Nepalo", "pl" -> "Nepal")),
        EnumOption("fi", I18nString("eo" -> "Finnlando", "pl" -> "Finlandia")),
        EnumOption("sm", I18nString("eo" -> "San-Marino", "pl" -> "San Marino")),
        EnumOption("so", I18nString("eo" -> "Somalujo", "pl" -> "Somalia")),
        EnumOption("nz", I18nString("eo" -> "Nov-Zelando", "pl" -> "Nowa Zelandia")),
        EnumOption("sc", I18nString("eo" -> "Sej\u015deloj", "pl" -> "Seszele")),
        EnumOption("sb", I18nString("eo" -> "Salomonoj", "pl" -> "Wyspy Salomona")),
        EnumOption("se", I18nString("eo" -> "Svedujo", "pl" -> "Szwecja")),
        EnumOption("sd", I18nString("eo" -> "Sudano", "pl" -> "Sudan")),
        EnumOption("sg", I18nString("eo" -> "Singapuro", "pl" -> "Singapur")),
        EnumOption("to", I18nString("eo" -> "Tongo", "pl" -> "Tonga")),
        EnumOption("sy", I18nString("eo" -> "Sirio", "pl" -> "Syria")),
        EnumOption("na", I18nString("eo" -> "Namibio", "pl" -> "Namibia")),
        EnumOption("ng", I18nString("eo" -> "Ni\u011derio", "pl" -> "Nigeria")),
        EnumOption("ne", I18nString("eo" -> "Ni\u011dero", "pl" -> "Niger")),
        EnumOption("fr", I18nString("eo" -> "Francujo", "pl" -> "Francja")),
        EnumOption("ni", I18nString("eo" -> "Nikaragvo", "pl" -> "Nikaragua")),
        EnumOption("no", I18nString("eo" -> "Norvegujo", "pl" -> "Norwegia")),
        EnumOption("nl", I18nString("eo" -> "Nederlando", "pl" -> "Holandia")),
        EnumOption("sv", I18nString("eo" -> "Salvadoro", "pl" -> "Salwador")),
        EnumOption("tg", I18nString("eo" -> "Togolo", "pl" -> "Togo")),
        EnumOption("ve", I18nString("eo" -> "Venezuelo", "pl" -> "Wenezuela")),
        EnumOption("mz", I18nString("eo" -> "Mozambiko", "pl" -> "Mozambik")),
        EnumOption("my", I18nString("eo" -> "Malajzio", "pl" -> "Malezja")),
        EnumOption("mx", I18nString("eo" -> "Meksiko", "pl" -> "Meksyk")),
        EnumOption("mr", I18nString("eo" -> "Ma\u016dritanujo", "pl" -> "Mauretania")),
        EnumOption("mw", I18nString("eo" -> "Malavio", "pl" -> "Malawi")),
        EnumOption("mv", I18nString("eo" -> "Maldivoj", "pl" -> "Malediwy")),
        EnumOption("mu", I18nString("eo" -> "Ma\u016dricio", "pl" -> "Mauritius")),
        EnumOption("mt", I18nString("eo" -> "Malto", "pl" -> "Malta")),
        EnumOption("mk", I18nString("eo" -> "Makedonujo", "pl" -> "Macedonia")),
        EnumOption("mh", I18nString("eo" -> "Mar\u015daloj", "pl" -> "Wyspy Marshalla")),
        EnumOption("mn", I18nString("eo" -> "Mongolujo", "pl" -> "Mongolia")),
        EnumOption("mm", I18nString("eo" -> "Mjanmao", "pl" -> "Birma")),
        EnumOption("ml", I18nString("eo" -> "Malio", "pl" -> "Mali")),
        EnumOption("mc", I18nString("eo" -> "Monako", "pl" -> "Monako")),
        EnumOption("vc", I18nString("eo" -> "Sent-Vincento kaj la Grenadinoj", "pl" -> "Saint Vincent i Grenadyny")),
        EnumOption("ma", I18nString("eo" -> "Maroko", "pl" -> "Maroko")),
        EnumOption("ru", I18nString("eo" -> "Rusujo", "pl" -> "Rosja")),
        EnumOption("mg", I18nString("eo" -> "Madagaskaro", "pl" -> "Madagaskar")),
        EnumOption("me", I18nString("eo" -> "ME", "pl" -> "Czarnog\u00f3ra")),
        EnumOption("md", I18nString("eo" -> "Moldavujo", "pl" -> "Mo\u0142dawia")),
        EnumOption("sl", I18nString("eo" -> "Siera-Leono", "pl" -> "Sierra Leone")),
        EnumOption("az", I18nString("eo" -> "Azerbaj\u011dano", "pl" -> "Azerbejd\u017can")),
        EnumOption("au", I18nString("eo" -> "A\u016dstralio", "pl" -> "Australia")),
        EnumOption("at", I18nString("eo" -> "A\u016dstrujo", "pl" -> "Austria")),
        EnumOption("ar", I18nString("eo" -> "Argentino", "pl" -> "Argentyna")),
        EnumOption("ao", I18nString("eo" -> "Angolo", "pl" -> "Angola")),
        EnumOption("am", I18nString("eo" -> "Armenujo", "pl" -> "Armenia")),
        EnumOption("al", I18nString("eo" -> "Albanujo", "pl" -> "Albania")),
        EnumOption("ag", I18nString("eo" -> "Antigvo-Barbudo", "pl" -> "Antigua i Barbuda")),
        EnumOption("af", I18nString("eo" -> "Afganujo", "pl" -> "Afganistan")),
        EnumOption("ae", I18nString("eo" -> "Unui\u011dintaj Arabaj Emirlandos", "pl" -> "Zjednoczone Emiraty Arabskie")),
        EnumOption("ad", I18nString("eo" -> "Andoro", "pl" -> "Andora")),
        EnumOption("ly", I18nString("eo" -> "Libio", "pl" -> "Libia")),
        EnumOption("lr", I18nString("eo" -> "Liberio", "pl" -> "Liberia")),
        EnumOption("ls", I18nString("eo" -> "Lesoto", "pl" -> "Lesotho")),
        EnumOption("lt", I18nString("eo" -> "Litovujo", "pl" -> "Litwa")),
        EnumOption("lu", I18nString("eo" -> "Luksemburgo", "pl" -> "Luksemburg")),
        EnumOption("lv", I18nString("eo" -> "Latvujo", "pl" -> "\u0141otwa")),
        EnumOption("li", I18nString("eo" -> "Li\u0125ten\u015dtejno", "pl" -> "Liechtenstein")),
        EnumOption("ye", I18nString("eo" -> "Jemeno", "pl" -> "Jemen")),
        EnumOption("lk", I18nString("eo" -> "Sri-Lanko", "pl" -> "Sri Lanka")),
        EnumOption("sz", I18nString("eo" -> "Svazilando", "pl" -> "Suazi")),
        EnumOption("la", I18nString("eo" -> "Laoso", "pl" -> "Laos")),
        EnumOption("lb", I18nString("eo" -> "Libano", "pl" -> "Liban")),
        EnumOption("lc", I18nString("eo" -> "Sent-Lucio", "pl" -> "Saint Lucia")),
        EnumOption("zw", I18nString("eo" -> "Zimbabvo", "pl" -> "Zimbabwe")),
        EnumOption("ir", I18nString("eo" -> "Irano", "pl" -> "Iran")),
        EnumOption("nr", I18nString("eo" -> "Nauro", "pl" -> "Nauru")),
        EnumOption("us", I18nString("eo" -> "Usono", "pl" -> "Stany Zjednoczone")),
        EnumOption("sn", I18nString("eo" -> "Senegalo", "pl" -> "Senegal")),
        EnumOption("dz", I18nString("eo" -> "Al\u011derio", "pl" -> "Algieria")),
        EnumOption("sk", I18nString("eo" -> "Slovakujo", "pl" -> "S\u0142owacja")),
        EnumOption("pw", I18nString("eo" -> "Bela\u016do", "pl" -> "Palau")),
        EnumOption("ro", I18nString("eo" -> "Rumanujo", "pl" -> "Rumunia")),
        EnumOption("de", I18nString("eo" -> "Germanujo", "pl" -> "Niemcy")),
        EnumOption("dj", I18nString("eo" -> "\u011cibutio", "pl" -> "D\u017cibuti")),
        EnumOption("dk", I18nString("eo" -> "Danujo", "pl" -> "Dania")),
        EnumOption("dm", I18nString("eo" -> "Dominiko", "pl" -> "Dominika")),
        EnumOption("do", I18nString("eo" -> "Domingo", "pl" -> "Republika Dominika\u0144ska")),
        EnumOption("ke", I18nString("eo" -> "Kenjo", "pl" -> "Kenia")),
        EnumOption("pl", I18nString("eo" -> "Pollando", "pl" -> "Polska")),
        EnumOption("kg", I18nString("eo" -> "Kirgizistano", "pl" -> "Kirgistan")),
        EnumOption("sa", I18nString("eo" -> "Sa\u016dda Arabujo", "pl" -> "Arabia Saudyjska")),
        EnumOption("ki", I18nString("eo" -> "Kiribato", "pl" -> "Kiribati")),
        EnumOption("kh", I18nString("eo" -> "Kambo\u011do", "pl" -> "Kambod\u017ca")),
        EnumOption("tj", I18nString("eo" -> "Ta\u011dikujo", "pl" -> "Tad\u017cykistan")),
        EnumOption("fm", I18nString("eo" -> "Mikronezio", "pl" -> "Federalne Stany Mikronezji")),
        EnumOption("km", I18nString("eo" -> "Komoroj", "pl" -> "Komory")),
        EnumOption("tm", I18nString("eo" -> "Turkmenujo", "pl" -> "Turkmenistan")),
        EnumOption("tn", I18nString("eo" -> "Tunizio", "pl" -> "Tunezja")),
        EnumOption("kn", I18nString("eo" -> "Sent-Kristofo kaj Neviso", "pl" -> "Saint Kitts i Nevis")),
        EnumOption("kp", I18nString("eo" -> "Nord-Koreo", "pl" -> "Korea P\u00f3\u0142nocna")),
        EnumOption("tr", I18nString("eo" -> "Turkujo", "pl" -> "Turcja")),
        EnumOption("kr", I18nString("eo" -> "Sud-Koreo", "pl" -> "Korea Po\u0142udniowa")),
        EnumOption("tt", I18nString("eo" -> "Trinidado kaj Tobago", "pl" -> "Trynidad i Tobago")),
        EnumOption("kw", I18nString("eo" -> "Kuvajto", "pl" -> "Kuwejt")),
        EnumOption("tw", I18nString("eo" -> "Tajvano", "pl" -> "Tajwan")),
        EnumOption("tz", I18nString("eo" -> "Tanzanio", "pl" -> "Tanzania")),
        EnumOption("kz", I18nString("eo" -> "Kaza\u0125stano", "pl" -> "Kazachstan")),
        EnumOption("vu", I18nString("eo" -> "Vanuatuo", "pl" -> "Vanuatu")),
        EnumOption("ws", I18nString("eo" -> "Samoo", "pl" -> "Samoa")),
        EnumOption("sr", I18nString("eo" -> "Surinamo", "pl" -> "Surinam")),
        EnumOption("jp", I18nString("eo" -> "Japanujo", "pl" -> "Japonia")),
        EnumOption("jo", I18nString("eo" -> "Jordanio", "pl" -> "Jordania")),
        EnumOption("jm", I18nString("eo" -> "Jamajko", "pl" -> "Jamajka")),
        EnumOption("qa", I18nString("eo" -> "Kataro", "pl" -> "Katar")),
        EnumOption("bw", I18nString("eo" -> "Bocvano", "pl" -> "Botswana")),
        EnumOption("bt", I18nString("eo" -> "Butano", "pl" -> "Bhutan")),
        EnumOption("zm", I18nString("eo" -> "Zambio", "pl" -> "Zambia")),
        EnumOption("br", I18nString("eo" -> "Brazilo", "pl" -> "Brazylia")),
        EnumOption("bs", I18nString("eo" -> "Bahamoj", "pl" -> "Bahamy")),
        EnumOption("bz", I18nString("eo" -> "Belizo", "pl" -> "Belize")),
        EnumOption("by", I18nString("eo" -> "Belorusujo", "pl" -> "Bia\u0142oru\u015b")),
        EnumOption("bf", I18nString("eo" -> "Burkino", "pl" -> "Burkina Faso")),
        EnumOption("bg", I18nString("eo" -> "Bulgarujo", "pl" -> "Bu\u0142garia")),
        EnumOption("bd", I18nString("eo" -> "Banglade\u015do", "pl" -> "Bangladesz")),
        EnumOption("be", I18nString("eo" -> "Belgujo", "pl" -> "Belgia")),
        EnumOption("bb", I18nString("eo" -> "Barbado", "pl" -> "Barbados")),
        EnumOption("ba", I18nString("eo" -> "Bosnio-Hercegovino", "pl" -> "Bo\u015bnia i Hercegowina")),
        EnumOption("bn", I18nString("eo" -> "Brunejo", "pl" -> "Brunei Darussalam")),
        EnumOption("bo", I18nString("eo" -> "Bolivio", "pl" -> "Boliwia")),
        EnumOption("bj", I18nString("eo" -> "Benino", "pl" -> "Benin")),
        EnumOption("th", I18nString("eo" -> "Tajlando", "pl" -> "Tajlandia")),
        EnumOption("bh", I18nString("eo" -> "Barejno", "pl" -> "Bahrajn")),
        EnumOption("bi", I18nString("eo" -> "Burundo", "pl" -> "Burundi")),
        EnumOption("ie", I18nString("eo" -> "Irlando", "pl" -> "Irlandia")),
        EnumOption("id", I18nString("eo" -> "Indonezio", "pl" -> "Indonezja")),
        EnumOption("in", I18nString("eo" -> "Hindujo", "pl" -> "Indie")),
        EnumOption("il", I18nString("eo" -> "Israelo", "pl" -> "Izrael")),
        EnumOption("st", I18nString("eo" -> "Sao-Tomeo kaj Principeo", "pl" -> "Wyspy \u015awi\u0119tego Tomasza i Ksi\u0105\u017c\u0119ca")),
        EnumOption("rw", I18nString("eo" -> "Ruando", "pl" -> "Rwanda")),
        EnumOption("it", I18nString("eo" -> "Italujo", "pl" -> "W\u0142ochy")),
        EnumOption("is", I18nString("eo" -> "Islando", "pl" -> "Islandia")),
        EnumOption("rs", I18nString("eo" -> "RS", "pl" -> "Serbia")),
        EnumOption("iq", I18nString("eo" -> "Irako", "pl" -> "Irak")),
        EnumOption("gd", I18nString("eo" -> "Grenado", "pl" -> "Grenada")),
        EnumOption("es", I18nString("eo" -> "Hispanujo", "pl" -> "Hiszpania")),
        EnumOption("er", I18nString("eo" -> "Eritreo", "pl" -> "Erytrea")),
        EnumOption("et", I18nString("eo" -> "Etiopujo", "pl" -> "Etiopia")),
        EnumOption("td", I18nString("eo" -> "\u0108ado", "pl" -> "Czad")),
        EnumOption("tl", I18nString("eo" -> "TL", "pl" -> "Timor Wschodni")),
        EnumOption("ec", I18nString("eo" -> "Ekvadoro", "pl" -> "Ekwador")),
        EnumOption("eg", I18nString("eo" -> "Egipto", "pl" -> "Egipt")),
        EnumOption("ee", I18nString("eo" -> "Estonujo", "pl" -> "Estonia")),
        EnumOption("va", I18nString("eo" -> "Vatikano", "pl" -> "Watykan")),
        EnumOption("vn", I18nString("eo" -> "Vjetnamo", "pl" -> "Wietnam")),
        EnumOption("ua", I18nString("eo" -> "Ukrajno", "pl" -> "Ukraina")),
        EnumOption("ug", I18nString("eo" -> "Ugando", "pl" -> "Uganda")),
        EnumOption("hn", I18nString("eo" -> "Honduro", "pl" -> "Honduras")),
        EnumOption("ht", I18nString("eo" -> "Haitio", "pl" -> "Haiti")),
        EnumOption("hu", I18nString("eo" -> "Hungarujo", "pl" -> "W\u0119gry")),
        EnumOption("pt", I18nString("eo" -> "Portugalujo", "pl" -> "Portugalia")),
        EnumOption("hr", I18nString("eo" -> "Kroatujo", "pl" -> "Chorwacja")),
        EnumOption("uz", I18nString("eo" -> "Uzbekujo", "pl" -> "Uzbekistan")),
        EnumOption("uy", I18nString("eo" -> "Urugvajo", "pl" -> "Urugwaj")),
        EnumOption("py", I18nString("eo" -> "Paragvajo", "pl" -> "Paragwaj")),
        EnumOption("tv", I18nString("eo" -> "Tuvalo", "pl" -> "Tuvalu")),
        EnumOption("za", I18nString("eo" -> "Sud-Afriko", "pl" -> "Republika Po\u0142udniowej Afryki")),
        EnumOption("gm", I18nString("eo" -> "Gambio", "pl" -> "Gambia")),
        EnumOption("gn", I18nString("eo" -> "Gvineo", "pl" -> "Gwinea")),
        EnumOption("ph", I18nString("eo" -> "Filipinoj", "pl" -> "Filipiny")),
        EnumOption("gh", I18nString("eo" -> "Ganao", "pl" -> "Ghana")),
        EnumOption("pk", I18nString("eo" -> "Pakistano", "pl" -> "Pakistan")),
        EnumOption("ge", I18nString("eo" -> "Kartvelujo", "pl" -> "Gruzja")),
        EnumOption("pe", I18nString("eo" -> "Peruo", "pl" -> "Peru")),
        EnumOption("pg", I18nString("eo" -> "Papuo-Nov-Gvineo", "pl" -> "Papua Nowa Gwinea")),
        EnumOption("ga", I18nString("eo" -> "Gabono", "pl" -> "Gabon")),
        EnumOption("pa", I18nString("eo" -> "Panamo", "pl" -> "Panama")),
        EnumOption("gb", I18nString("eo" -> "Unui\u011dinta Re\u011dlando", "pl" -> "Wielka Brytania")),
        EnumOption("gy", I18nString("eo" -> "Gujano", "pl" -> "Gujana")),
        EnumOption("si", I18nString("eo" -> "Slovenujo", "pl" -> "S\u0142owenia")),
        EnumOption("om", I18nString("eo" -> "Omano", "pl" -> "Oman")),
        EnumOption("gt", I18nString("eo" -> "Gvatemalo", "pl" -> "Gwatemala")),
        EnumOption("gw", I18nString("eo" -> "Gvineo-Bisa\u016do", "pl" -> "Gwinea Bissau")),
        EnumOption("gq", I18nString("eo" -> "Ekvatora Gvineo", "pl" -> "Gwinea R\u00f3wnikowa")),
        EnumOption("gr", I18nString("eo" -> "Grekujo", "pl" -> "Grecja"))
      ).sortBy(_.caption("eo"))(pl.pej.util.EsperantoOrdering.ordering),
      notSelected = Some(EnumOption("nenio", I18n.po("bv. elekti landon")))
    )
  )

}
