package pl.pej.malpompaaligxilo

import pl.pej.malpompaaligxilo.form.{FieldName, Field}
import pl.pej.malpompaaligxilo.form.field.{EnumOption, SelectField}
import pl.pej.malpompaaligxilo.util._


package object jes2015 {
  implicit def tuple22enumOption(tuple2: (String, I18nable[String])): EnumOption =
    EnumOption(tuple2._1, tuple2._2)

  def countryField(implicit poCfg: PoCfg) = Field[EnumOption](
    name = "lando",
    caption = I18n.po("Lando"),
    required = true,
    `type` = SelectField(
      options = List[EnumOption](
        EnumOption("cy", I18nString("eo" -> "Kipro", "hu" -> "Ciprus", "pl" -> "Cypr")),
        EnumOption("cz", I18nString("eo" -> "Ĉeĥujo", "hu" -> "Csehország", "pl" -> "Czechy")),
        EnumOption("cr", I18nString("eo" -> "Kostariko", "hu" -> "Costa Rica", "pl" -> "Kostaryka")),
        EnumOption("cu", I18nString("eo" -> "Kubo", "hu" -> "Kuba", "pl" -> "Kuba")),
        EnumOption("cv", I18nString("eo" -> "Kabo-Verdo", "hu" -> "Zöld-foki Köztársaság", "pl" -> "Republika Zielonego Przylądka")),
  EnumOption("ci", I18nString("eo" -> "Ebur-Bordo", "hu" -> "Elefántcsontpart", "pl" -> "Wybrzeże Kości Słoniowej")),
  EnumOption("ch", I18nString("eo" -> "Svisujo", "hu" -> "Svájc", "pl" -> "Szwajcaria")),
  EnumOption("cm", I18nString("eo" -> "Kameruno", "hu" -> "Kamerun", "pl" -> "Kamerun")),
  EnumOption("cl", I18nString("eo" -> "Ĉilio", "hu" -> "Chile", "pl" -> "Chile")),
  EnumOption("co", I18nString("eo" -> "Kolombio", "hu" -> "Kolumbia", "pl" -> "Kolumbia")),
  EnumOption("cn", I18nString("eo" -> "Ĉinujo", "hu" -> "Kína", "pl" -> "Chiny")),
  EnumOption("ca", I18nString("eo" -> "Kanado", "hu" -> "Kanada", "pl" -> "Kanada")),
  EnumOption("cd", I18nString("eo" -> "Demokratia Respubliko Kongo", "hu" -> "Kongó - Kinshasa", "pl" -> "Demokratyczna Republika Konga")),
  EnumOption("cg", I18nString("eo" -> "Kongolo", "hu" -> "Kongó", "pl" -> "Kongo")),
  EnumOption("cf", I18nString("eo" -> "Centr-Afrika Respubliko", "hu" -> "Közép-afrikai Köztársaság", "pl" -> "Republika Środkowoafrykańska")),
  EnumOption("fj", I18nString("eo" -> "Fiĝoj", "hu" -> "Fidzsi", "pl" -> "Fidżi")),
  EnumOption("np", I18nString("eo" -> "Nepalo", "hu" -> "Nepál", "pl" -> "Nepal")),
  EnumOption("fi", I18nString("eo" -> "Finnlando", "hu" -> "Finnország", "pl" -> "Finlandia")),
  EnumOption("sm", I18nString("eo" -> "San-Marino", "hu" -> "San Marino", "pl" -> "San Marino")),
  EnumOption("so", I18nString("eo" -> "Somalujo", "hu" -> "Szomália", "pl" -> "Somalia")),
  EnumOption("nz", I18nString("eo" -> "Nov-Zelando", "hu" -> "Új-Zéland", "pl" -> "Nowa Zelandia")),
  EnumOption("sc", I18nString("eo" -> "Sejŝeloj", "hu" -> "Seychelle-szigetek", "pl" -> "Seszele")),
  EnumOption("sb", I18nString("eo" -> "Salomonoj", "hu" -> "Salamon-szigetek", "pl" -> "Wyspy Salomona")),
  EnumOption("se", I18nString("eo" -> "Svedujo", "hu" -> "Svédország", "pl" -> "Szwecja")),
  EnumOption("sd", I18nString("eo" -> "Sudano", "hu" -> "Szudán", "pl" -> "Sudan")),
  EnumOption("sg", I18nString("eo" -> "Singapuro", "hu" -> "Szingapúr", "pl" -> "Singapur")),
  EnumOption("to", I18nString("eo" -> "Tongo", "hu" -> "Tonga", "pl" -> "Tonga")),
  EnumOption("sy", I18nString("eo" -> "Sirio", "hu" -> "Szíria", "pl" -> "Syria")),
  EnumOption("na", I18nString("eo" -> "Namibio", "hu" -> "Namíbia", "pl" -> "Namibia")),
  EnumOption("ng", I18nString("eo" -> "Niĝerio", "hu" -> "Nigéria", "pl" -> "Nigeria")),
  EnumOption("ne", I18nString("eo" -> "Niĝero", "hu" -> "Niger", "pl" -> "Niger")),
  EnumOption("fr", I18nString("eo" -> "Francujo", "hu" -> "Franciaország", "pl" -> "Francja")),
  EnumOption("ni", I18nString("eo" -> "Nikaragvo", "hu" -> "Nicaragua", "pl" -> "Nikaragua")),
  EnumOption("no", I18nString("eo" -> "Norvegujo", "hu" -> "Norvégia", "pl" -> "Norwegia")),
  EnumOption("nl", I18nString("eo" -> "Nederlando", "hu" -> "Hollandia", "pl" -> "Holandia")),
  EnumOption("sv", I18nString("eo" -> "Salvadoro", "hu" -> "Salvador", "pl" -> "Salwador")),
  EnumOption("tg", I18nString("eo" -> "Togolo", "hu" -> "Togo", "pl" -> "Togo")),
  EnumOption("ve", I18nString("eo" -> "Venezuelo", "hu" -> "Venezuela", "pl" -> "Wenezuela")),
  EnumOption("mz", I18nString("eo" -> "Mozambiko", "hu" -> "Mozambik", "pl" -> "Mozambik")),
  EnumOption("my", I18nString("eo" -> "Malajzio", "hu" -> "Malajzia", "pl" -> "Malezja")),
  EnumOption("mx", I18nString("eo" -> "Meksiko", "hu" -> "Mexikó", "pl" -> "Meksyk")),
  EnumOption("mr", I18nString("eo" -> "Maŭritanujo", "hu" -> "Mauritánia", "pl" -> "Mauretania")),
  EnumOption("mw", I18nString("eo" -> "Malavio", "hu" -> "Malawi", "pl" -> "Malawi")),
  EnumOption("mv", I18nString("eo" -> "Maldivoj", "hu" -> "Maldív-szigetek", "pl" -> "Malediwy")),
  EnumOption("mu", I18nString("eo" -> "Maŭricio", "hu" -> "Mauritius", "pl" -> "Mauritius")),
  EnumOption("mt", I18nString("eo" -> "Malto", "hu" -> "Málta", "pl" -> "Malta")),
  EnumOption("mk", I18nString("eo" -> "Makedonujo", "hu" -> "Macedónia", "pl" -> "Macedonia")),
  EnumOption("mh", I18nString("eo" -> "Marŝaloj", "hu" -> "Marshall-szigetek", "pl" -> "Wyspy Marshalla")),
  EnumOption("mn", I18nString("eo" -> "Mongolujo", "hu" -> "Mongólia", "pl" -> "Mongolia")),
  EnumOption("mm", I18nString("eo" -> "Mjanmao", "hu" -> "Mianmar", "pl" -> "Birma")),
  EnumOption("ml", I18nString("eo" -> "Malio", "hu" -> "Mali", "pl" -> "Mali")),
  EnumOption("mc", I18nString("eo" -> "Monako", "hu" -> "Monaco", "pl" -> "Monako")),
  EnumOption("vc", I18nString("eo" -> "Sent-Vincento kaj la Grenadinoj", "hu" -> "Saint Vincent és Grenadines", "pl" -> "Saint Vincent i Grenadyny")),
  EnumOption("ma", I18nString("eo" -> "Maroko", "hu" -> "Marokkó", "pl" -> "Maroko")),
  EnumOption("ru", I18nString("eo" -> "Rusujo", "hu" -> "Oroszország", "pl" -> "Rosja")),
  EnumOption("mg", I18nString("eo" -> "Madagaskaro", "hu" -> "Madagaszkár", "pl" -> "Madagaskar")),
  EnumOption("me", I18nString("eo" -> "ME", "hu" -> "Montenegró", "pl" -> "Czarnogóra")),
  EnumOption("md", I18nString("eo" -> "Moldavujo", "hu" -> "Moldova", "pl" -> "Mołdawia")),
  EnumOption("sl", I18nString("eo" -> "Siera-Leono", "hu" -> "Sierra Leone", "pl" -> "Sierra Leone")),
  EnumOption("az", I18nString("eo" -> "Azerbajĝano", "hu" -> "Azerbajdzsán", "pl" -> "Azerbejdżan")),
  EnumOption("au", I18nString("eo" -> "Aŭstralio", "hu" -> "Ausztrália", "pl" -> "Australia")),
  EnumOption("at", I18nString("eo" -> "Aŭstrujo", "hu" -> "Ausztria", "pl" -> "Austria")),
  EnumOption("ar", I18nString("eo" -> "Argentino", "hu" -> "Argentína", "pl" -> "Argentyna")),
  EnumOption("ao", I18nString("eo" -> "Angolo", "hu" -> "Angola", "pl" -> "Angola")),
  EnumOption("am", I18nString("eo" -> "Armenujo", "hu" -> "Örményország", "pl" -> "Armenia")),
  EnumOption("al", I18nString("eo" -> "Albanujo", "hu" -> "Albánia", "pl" -> "Albania")),
  EnumOption("ag", I18nString("eo" -> "Antigvo-Barbudo", "hu" -> "Antigua és Barbuda", "pl" -> "Antigua i Barbuda")),
  EnumOption("af", I18nString("eo" -> "Afganujo", "hu" -> "Afganisztán", "pl" -> "Afganistan")),
  EnumOption("ae", I18nString("eo" -> "Unuiĝintaj Arabaj Emirlandos", "hu" -> "Egyesült Arab Emirátus", "pl" -> "Zjednoczone Emiraty Arabskie")),
  EnumOption("ad", I18nString("eo" -> "Andoro", "hu" -> "Andorra", "pl" -> "Andora")),
  EnumOption("ly", I18nString("eo" -> "Libio", "hu" -> "Líbia", "pl" -> "Libia")),
  EnumOption("lr", I18nString("eo" -> "Liberio", "hu" -> "Libéria", "pl" -> "Liberia")),
  EnumOption("ls", I18nString("eo" -> "Lesoto", "hu" -> "Lesotho", "pl" -> "Lesotho")),
  EnumOption("lt", I18nString("eo" -> "Litovujo", "hu" -> "Litvánia", "pl" -> "Litwa")),
  EnumOption("lu", I18nString("eo" -> "Luksemburgo", "hu" -> "Luxemburg", "pl" -> "Luksemburg")),
  EnumOption("lv", I18nString("eo" -> "Latvujo", "hu" -> "Lettország", "pl" -> "Łotwa")),
  EnumOption("li", I18nString("eo" -> "Liĥtenŝtejno", "hu" -> "Liechtenstein", "pl" -> "Liechtenstein")),
  EnumOption("ye", I18nString("eo" -> "Jemeno", "hu" -> "Jemen", "pl" -> "Jemen")),
  EnumOption("lk", I18nString("eo" -> "Sri-Lanko", "hu" -> "Srí Lanka", "pl" -> "Sri Lanka")),
  EnumOption("sz", I18nString("eo" -> "Svazilando", "hu" -> "Szváziföld", "pl" -> "Suazi")),
  EnumOption("la", I18nString("eo" -> "Laoso", "hu" -> "Laosz", "pl" -> "Laos")),
  EnumOption("lb", I18nString("eo" -> "Libano", "hu" -> "Libanon", "pl" -> "Liban")),
  EnumOption("lc", I18nString("eo" -> "Sent-Lucio", "hu" -> "Santa Lucia", "pl" -> "Saint Lucia")),
  EnumOption("zw", I18nString("eo" -> "Zimbabvo", "hu" -> "Zimbabwe", "pl" -> "Zimbabwe")),
  EnumOption("ir", I18nString("eo" -> "Irano", "hu" -> "Irán", "pl" -> "Iran")),
  EnumOption("nr", I18nString("eo" -> "Nauro", "hu" -> "Nauru", "pl" -> "Nauru")),
  EnumOption("us", I18nString("eo" -> "Usono", "hu" -> "Egyesült Államok", "pl" -> "Stany Zjednoczone")),
  EnumOption("sn", I18nString("eo" -> "Senegalo", "hu" -> "Szenegál", "pl" -> "Senegal")),
  EnumOption("dz", I18nString("eo" -> "Alĝerio", "hu" -> "Algéria", "pl" -> "Algieria")),
  EnumOption("sk", I18nString("eo" -> "Slovakujo", "hu" -> "Szlovákia", "pl" -> "Słowacja")),
  EnumOption("pw", I18nString("eo" -> "Belaŭo", "hu" -> "Palau", "pl" -> "Palau")),
  EnumOption("ro", I18nString("eo" -> "Rumanujo", "hu" -> "Románia", "pl" -> "Rumunia")),
  EnumOption("de", I18nString("eo" -> "Germanujo", "hu" -> "Németország", "pl" -> "Niemcy")),
  EnumOption("dj", I18nString("eo" -> "Ĝibutio", "hu" -> "Dzsibuti", "pl" -> "Dżibuti")),
  EnumOption("dk", I18nString("eo" -> "Danujo", "hu" -> "Dánia", "pl" -> "Dania")),
  EnumOption("dm", I18nString("eo" -> "Dominiko", "hu" -> "Dominika", "pl" -> "Dominika")),
  EnumOption("do", I18nString("eo" -> "Domingo", "hu" -> "Dominikai Köztársaság", "pl" -> "Republika Dominikańska")),
  EnumOption("ke", I18nString("eo" -> "Kenjo", "hu" -> "Kenya", "pl" -> "Kenia")),
  EnumOption("pl", I18nString("eo" -> "Pollando", "hu" -> "Lengyelország", "pl" -> "Polska")),
  EnumOption("kg", I18nString("eo" -> "Kirgizistano", "hu" -> "Kirgizisztán", "pl" -> "Kirgistan")),
  EnumOption("sa", I18nString("eo" -> "Saŭda Arabujo", "hu" -> "Szaúd-Arábia", "pl" -> "Arabia Saudyjska")),
  EnumOption("ki", I18nString("eo" -> "Kiribato", "hu" -> "Kiribati", "pl" -> "Kiribati")),
  EnumOption("kh", I18nString("eo" -> "Kamboĝo", "hu" -> "Kambodzsa", "pl" -> "Kambodża")),
  EnumOption("tj", I18nString("eo" -> "Taĝikujo", "hu" -> "Tadzsikisztán", "pl" -> "Tadżykistan")),
  EnumOption("fm", I18nString("eo" -> "Mikronezio", "hu" -> "Mikronézia", "pl" -> "Federalne Stany Mikronezji")),
  EnumOption("km", I18nString("eo" -> "Komoroj", "hu" -> "Comore-szigetek", "pl" -> "Komory")),
  EnumOption("tm", I18nString("eo" -> "Turkmenujo", "hu" -> "Türkmenisztán", "pl" -> "Turkmenistan")),
  EnumOption("tn", I18nString("eo" -> "Tunizio", "hu" -> "Tunézia", "pl" -> "Tunezja")),
  EnumOption("kn", I18nString("eo" -> "Sent-Kristofo kaj Neviso", "hu" -> "Saint Kitts és Nevis", "pl" -> "Saint Kitts i Nevis")),
  EnumOption("kp", I18nString("eo" -> "Nord-Koreo", "hu" -> "Észak-Korea", "pl" -> "Korea Północna")),
  EnumOption("tr", I18nString("eo" -> "Turkujo", "hu" -> "Törökország", "pl" -> "Turcja")),
  EnumOption("kr", I18nString("eo" -> "Sud-Koreo", "hu" -> "Dél-Korea", "pl" -> "Korea Południowa")),
  EnumOption("tt", I18nString("eo" -> "Trinidado kaj Tobago", "hu" -> "Trinidad és Tobago", "pl" -> "Trynidad i Tobago")),
  EnumOption("kw", I18nString("eo" -> "Kuvajto", "hu" -> "Kuvait", "pl" -> "Kuwejt")),
  EnumOption("tw", I18nString("eo" -> "Tajvano", "hu" -> "Tajvan", "pl" -> "Tajwan")),
  EnumOption("tz", I18nString("eo" -> "Tanzanio", "hu" -> "Tanzánia", "pl" -> "Tanzania")),
  EnumOption("kz", I18nString("eo" -> "Kazaĥstano", "hu" -> "Kazahsztán", "pl" -> "Kazachstan")),
  EnumOption("vu", I18nString("eo" -> "Vanuatuo", "hu" -> "Vanuatu", "pl" -> "Vanuatu")),
  EnumOption("ws", I18nString("eo" -> "Samoo", "hu" -> "Szamoa", "pl" -> "Samoa")),
  EnumOption("sr", I18nString("eo" -> "Surinamo", "hu" -> "Suriname", "pl" -> "Surinam")),
  EnumOption("jp", I18nString("eo" -> "Japanujo", "hu" -> "Japán", "pl" -> "Japonia")),
  EnumOption("jo", I18nString("eo" -> "Jordanio", "hu" -> "Jordánia", "pl" -> "Jordania")),
  EnumOption("jm", I18nString("eo" -> "Jamajko", "hu" -> "Jamaica", "pl" -> "Jamajka")),
  EnumOption("qa", I18nString("eo" -> "Kataro", "hu" -> "Katar", "pl" -> "Katar")),
  EnumOption("bw", I18nString("eo" -> "Bocvano", "hu" -> "Botswana", "pl" -> "Botswana")),
  EnumOption("bt", I18nString("eo" -> "Butano", "hu" -> "Bhután", "pl" -> "Bhutan")),
  EnumOption("zm", I18nString("eo" -> "Zambio", "hu" -> "Zambia", "pl" -> "Zambia")),
  EnumOption("br", I18nString("eo" -> "Brazilo", "hu" -> "Brazília", "pl" -> "Brazylia")),
  EnumOption("bs", I18nString("eo" -> "Bahamoj", "hu" -> "Bahamák", "pl" -> "Bahamy")),
  EnumOption("bz", I18nString("eo" -> "Belizo", "hu" -> "Belize", "pl" -> "Belize")),
  EnumOption("by", I18nString("eo" -> "Belorusujo", "hu" -> "Fehéroroszország", "pl" -> "Białoruś")),
  EnumOption("bf", I18nString("eo" -> "Burkino", "hu" -> "Burkina Faso", "pl" -> "Burkina Faso")),
  EnumOption("bg", I18nString("eo" -> "Bulgarujo", "hu" -> "Bulgária", "pl" -> "Bułgaria")),
  EnumOption("bd", I18nString("eo" -> "Bangladeŝo", "hu" -> "Banglades", "pl" -> "Bangladesz")),
  EnumOption("be", I18nString("eo" -> "Belgujo", "hu" -> "Belgium", "pl" -> "Belgia")),
  EnumOption("bb", I18nString("eo" -> "Barbado", "hu" -> "Barbados", "pl" -> "Barbados")),
  EnumOption("ba", I18nString("eo" -> "Bosnio-Hercegovino", "hu" -> "Bosznia-Hercegovina", "pl" -> "Bośnia i Hercegowina")),
  EnumOption("bn", I18nString("eo" -> "Brunejo", "hu" -> "Brunei", "pl" -> "Brunei Darussalam")),
  EnumOption("bo", I18nString("eo" -> "Bolivio", "hu" -> "Bolívia", "pl" -> "Boliwia")),
  EnumOption("bj", I18nString("eo" -> "Benino", "hu" -> "Benin", "pl" -> "Benin")),
  EnumOption("th", I18nString("eo" -> "Tajlando", "hu" -> "Thaiföld", "pl" -> "Tajlandia")),
  EnumOption("bh", I18nString("eo" -> "Barejno", "hu" -> "Bahrein", "pl" -> "Bahrajn")),
  EnumOption("bi", I18nString("eo" -> "Burundo", "hu" -> "Burundi", "pl" -> "Burundi")),
  EnumOption("ie", I18nString("eo" -> "Irlando", "hu" -> "Írország", "pl" -> "Irlandia")),
  EnumOption("id", I18nString("eo" -> "Indonezio", "hu" -> "Indonézia", "pl" -> "Indonezja")),
  EnumOption("in", I18nString("eo" -> "Hindujo", "hu" -> "India", "pl" -> "Indie")),
  EnumOption("il", I18nString("eo" -> "Israelo", "hu" -> "Izrael", "pl" -> "Izrael")),
  EnumOption("st", I18nString("eo" -> "Sao-Tomeo kaj Principeo", "hu" -> "Sao Tomé és Príncipe", "pl" -> "Wyspy Świętego Tomasza i Książęca")),
  EnumOption("rw", I18nString("eo" -> "Ruando", "hu" -> "Ruanda", "pl" -> "Rwanda")),
  EnumOption("it", I18nString("eo" -> "Italujo", "hu" -> "Olaszország", "pl" -> "Włochy")),
  EnumOption("is", I18nString("eo" -> "Islando", "hu" -> "Izland", "pl" -> "Islandia")),
  EnumOption("rs", I18nString("eo" -> "RS", "hu" -> "Szerbia", "pl" -> "Serbia")),
  EnumOption("iq", I18nString("eo" -> "Irako", "hu" -> "Irak", "pl" -> "Irak")),
  EnumOption("gd", I18nString("eo" -> "Grenado", "hu" -> "Grenada", "pl" -> "Grenada")),
  EnumOption("es", I18nString("eo" -> "Hispanujo", "hu" -> "Spanyolország", "pl" -> "Hiszpania")),
  EnumOption("er", I18nString("eo" -> "Eritreo", "hu" -> "Eritrea", "pl" -> "Erytrea")),
  EnumOption("et", I18nString("eo" -> "Etiopujo", "hu" -> "Etiópia", "pl" -> "Etiopia")),
  EnumOption("td", I18nString("eo" -> "Ĉado", "hu" -> "Csád", "pl" -> "Czad")),
  EnumOption("tl", I18nString("eo" -> "TL", "hu" -> "Kelet-Timor", "pl" -> "Timor Wschodni")),
  EnumOption("ec", I18nString("eo" -> "Ekvadoro", "hu" -> "Ecuador", "pl" -> "Ekwador")),
  EnumOption("eg", I18nString("eo" -> "Egipto", "hu" -> "Egyiptom", "pl" -> "Egipt")),
  EnumOption("ee", I18nString("eo" -> "Estonujo", "hu" -> "Észtország", "pl" -> "Estonia")),
  EnumOption("va", I18nString("eo" -> "Vatikano", "hu" -> "Vatikán", "pl" -> "Watykan")),
  EnumOption("vn", I18nString("eo" -> "Vjetnamo", "hu" -> "Vietnam", "pl" -> "Wietnam")),
  EnumOption("ua", I18nString("eo" -> "Ukrajno", "hu" -> "Ukrajna", "pl" -> "Ukraina")),
  EnumOption("ug", I18nString("eo" -> "Ugando", "hu" -> "Uganda", "pl" -> "Uganda")),
  EnumOption("hn", I18nString("eo" -> "Honduro", "hu" -> "Honduras", "pl" -> "Honduras")),
  EnumOption("ht", I18nString("eo" -> "Haitio", "hu" -> "Haiti", "pl" -> "Haiti")),
  EnumOption("hu", I18nString("eo" -> "Hungarujo", "hu" -> "Magyarország", "pl" -> "Węgry")),
  EnumOption("pt", I18nString("eo" -> "Portugalujo", "hu" -> "Portugália", "pl" -> "Portugalia")),
  EnumOption("hr", I18nString("eo" -> "Kroatujo", "hu" -> "Horvátország", "pl" -> "Chorwacja")),
  EnumOption("uz", I18nString("eo" -> "Uzbekujo", "hu" -> "Üzbegisztán", "pl" -> "Uzbekistan")),
  EnumOption("uy", I18nString("eo" -> "Urugvajo", "hu" -> "Uruguay", "pl" -> "Urugwaj")),
  EnumOption("py", I18nString("eo" -> "Paragvajo", "hu" -> "Paraguay", "pl" -> "Paragwaj")),
  EnumOption("tv", I18nString("eo" -> "Tuvalo", "hu" -> "Tuvalu", "pl" -> "Tuvalu")),
  EnumOption("za", I18nString("eo" -> "Sud-Afriko", "hu" -> "Dél-Afrika", "pl" -> "Republika Południowej Afryki")),
  EnumOption("gm", I18nString("eo" -> "Gambio", "hu" -> "Gambia", "pl" -> "Gambia")),
  EnumOption("gn", I18nString("eo" -> "Gvineo", "hu" -> "Guinea", "pl" -> "Gwinea")),
  EnumOption("ph", I18nString("eo" -> "Filipinoj", "hu" -> "Fülöp-szigetek", "pl" -> "Filipiny")),
  EnumOption("gh", I18nString("eo" -> "Ganao", "hu" -> "Ghána", "pl" -> "Ghana")),
  EnumOption("pk", I18nString("eo" -> "Pakistano", "hu" -> "Pakisztán", "pl" -> "Pakistan")),
  EnumOption("ge", I18nString("eo" -> "Kartvelujo", "hu" -> "Grúzia", "pl" -> "Gruzja")),
  EnumOption("pe", I18nString("eo" -> "Peruo", "hu" -> "Peru", "pl" -> "Peru")),
  EnumOption("pg", I18nString("eo" -> "Papuo-Nov-Gvineo", "hu" -> "Pápua Új-Guinea", "pl" -> "Papua Nowa Gwinea")),
  EnumOption("ga", I18nString("eo" -> "Gabono", "hu" -> "Gabon", "pl" -> "Gabon")),
  EnumOption("pa", I18nString("eo" -> "Panamo", "hu" -> "Panama", "pl" -> "Panama")),
  EnumOption("gb", I18nString("eo" -> "Unuiĝinta Reĝlando", "hu" -> "Egyesült Királyság", "pl" -> "Wielka Brytania")),
  EnumOption("gy", I18nString("eo" -> "Gujano", "hu" -> "Guyana", "pl" -> "Gujana")),
  EnumOption("si", I18nString("eo" -> "Slovenujo", "hu" -> "Szlovénia", "pl" -> "Słowenia")),
  EnumOption("om", I18nString("eo" -> "Omano", "hu" -> "Omán", "pl" -> "Oman")),
  EnumOption("gt", I18nString("eo" -> "Gvatemalo", "hu" -> "Guatemala", "pl" -> "Gwatemala")),
  EnumOption("gw", I18nString("eo" -> "Gvineo-Bisaŭo", "hu" -> "Guinea-Bissau", "pl" -> "Gwinea Bissau")),
  EnumOption("gq", I18nString("eo" -> "Ekvatora Gvineo", "hu" -> "Egyenlítői-Guinea", "pl" -> "Gwinea Równikowa")),
  EnumOption("gr", I18nString("eo" -> "Grekujo", "hu" -> "Görögország", "pl" -> "Grecja"))
      ).sortBy(_.caption("eo"))(pl.pej.util.EsperantoOrdering.ordering),
      notSelected = Some(EnumOption("nenio", I18n.po("bv. elekti landon")))
    )
  )

}
